[package]
name = "key-store"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[lib]
path = "src/key-store.rs"

[dependencies]
rusqlite = { version = "0.25", optional = true }
evercrypt = { version = "0.0.8", optional = true }
hpke = { version = "0.0.7", package = "hpke-rs", optional = true }
log = "0.4"
zeroize = { version = "1.3", features = ["zeroize_derive"] }
rand = "0.8"

[dev-dependencies]
pretty_env_logger = "0.4"
digest = "0.9"
sha2 = "0.9"

[features]
default = []
random = [] # Enable functions that require randomness such as key generation
hazmat = [] # ☣️ enable unsafe features
sqlite-backend = ["rusqlite"] # enable the builtin sqlite key store
evercrypt-backend = ["evercrypt", "hpke"]
