[package]
name = "key-store"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[lib]
path = "src/key-store.rs"

[dependencies]
rusqlite = "0.25"
evercrypt = "0.0.8"
hpke = { version = "0.0.7", package = "hpke-rs" }
log = "0.4"
zeroize = { version = "1.3", features = ["zeroize_derive"] }
openmls = { git = "https://github.com/openmls/openmls/", optional = true, branch = "main" }

[dev-dependencies]
pretty_env_logger = "0.4"

[features]
default = []
hazmat = [] # ☣️ enable unsafe features
